spring.application.name=hkboard_springboot09

server.port=9090

#비활성화 이유는 개발시 변경사항등을 바로 확인하기 위해
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

#DB설정
spring.datasource.dbcp2.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/hk
spring.datasource.username=root
spring.datasource.password=manager

#myBatis 설정
mybatis.type-aliases-package=com.hk.board.dtos
mybatis.mapper-locations=classpath:/mybatis/**/*.xml